### PR TITLE
OpenBSD support

### PR DESCRIPTION
**Pull request by buzzdeee**
The main part of this patch is getting the module to support managing asterisk on OpenBSD.
Tested on OpenBSD 5.6-current, with asterisk-11.14.1, and puppet-3.7.3.

While there, and because I run the future parser, there are some enhancements making the module work with the future parser. Additionally to that, a few minor changes, which puppet-lint told me about.

The most "drastic" change is in manifests/service.pp, in the service, I removed the fairly unportable, start, stop and restart parameters. The service type should be clever enough to figure that out on its own, at least it does so on OpenBSD ;)

Other changes is the introduction of general parameters: asteriskuser, asteriskgroup, which contain the username/groupname of the account running asterisk. Then the astbinary, which points to the 'asterisk' binary location. Further, the group 'root' in config.pp was changed to just the userid: 0.
On OpenBSD, and other *BSD, there is no group root', but group wheel, with gid 0.

please review and apply, or comment, so I can fix or rework as you like.

Sebastian

### CODE REVIEW

**Comment by runswithd6s** [comment]
Looks pretty good! I also noted the owner/group assignment in File and Concat specs should use a variable for better cross-platform support. Nicely done. I'll test on CentOS when I get in to the office tomorrow. I'm sure @giavac will test on Debian as well.

**Comment by runswithd6s** [comment]
You could potentially update the README.md file to indicate it has been tested on OpenBSD as well. (I should do that for CentOS 6.)

**Comment by giavac** [comment]
Thanks for the PR Sebastian, and Chad for the review. I will look into this ASAP.
A README update would be great, and possibly a comment about backward compatibility with the stock puppet version for BSD (unless it's already 3.7, of course). Regards.

**Comment by giavac** [comment]
Brilliant PR, thanks Sebastian, and welcome to the group of contributors.

**Pull request merged**
