### PR TITLE
Updated sip.conf management

### PR DESCRIPTION
**Pull request by runswithd6s**
- Moved sip.conf from `file` to `concat` resource
- Broke up sip.conf into three sections
- Added ::asterisk::config::device defined type
  - Allow multiple sip devices to be created

### CODE REVIEW

**Comment by runswithd6s** [comment]
Added a couple of cleanups.

**Comment by giavac** [comment]
Hey Chad,
I'm seeing this on debian wheezy with puppet 2.7.13:

root@ee79998f8b1c:/git/trulabs/puppet-asterisk# puppet apply -v tests/device.pp --modulepath modules/:/etc/puppet/modules --show_diff --noop
[...]
Syntax error at 'in'; expected '}' at /etc/puppet/modules/asterisk/manifests/config/device.pp:129 on node ee79998f8b1c

It works with puppet 3.7. Is there a way to make it back-compatible? Thanks.

**Comment by runswithd6s** [comment]
Ah, good question. We could do a case comparison. I'll be back in the office on Tuesday and can work something out.

**Comment by giavac** [comment]
Great, thanks again Chad.

**Comment by runswithd6s** [comment]
Updated.

**Comment by giavac** [comment]
Looking good to me (debian wheezy container with puppet 2.7) :-)
Thanks Chad.

**Pull request merged**
